#!/bin/bash

if command -v php &> /dev/null; then
    echo "PHP ok"
else
    echo "PHP is not installed."
fi

if command -v composer &> /dev/null; then
    echo "composer ok"
else
    echo "composer is not installed."
fi

if command -v docker-compose &> /dev/null; then
    echo "docker-compose ok"
else
    echo "docker-compose is not installed."
fi

if [ $# -ne 2 ]; then
    echo "Usage: $0 [laravel|mariadb] [up|down]"
    exit 1
fi

start_laravel() {
    php artisan serve
}

mariadb_command() {
    if [ "$1" = "up" ]; then
        if ! docker ps | grep -q example-app-db-1; then
            echo "Starting MariaDB..."
            docker-compose up -d db
        fi
    elif [ "$1" = "down" ]; then
        docker-compose down
    else
        echo "Invalid argument for MariaDB. Use 'up' or 'down'."
        exit 1
    fi
}

if [ "$1" = "laravel" ]; then
    if [ "$2" = "up" ]; then
        mariadb_command "up"
        start_laravel
    else
        echo "Invalid argument for Laravel. Use 'up' or 'down'."
        exit 1
    fi
elif [ "$1" = "mariadb" ]; then
    mariadb_command "$2"
else
    echo "Invalid service. Use 'laravel' or 'mariadb'."
    exit 1
fi
